sudo: required
language: go
go:
- 1.10.1

before_install:
- GLIDE_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
- GLIDE_TAG=$(curl -s https://glide.sh/version)
- GLIDE_LATEST_RELEASE_URL="https://github.com/Masterminds/glide/releases/download/${GLIDE_TAG}/glide-${GLIDE_TAG}-${GLIDE_OS_ARCH}.tar.gz"
- wget ${GLIDE_LATEST_RELEASE_URL} -O /tmp/glide.tar.gz
- mkdir /tmp/glide
- tar --directory=/tmp/glide -xvf /tmp/glide.tar.gz
- export PATH=$PATH:/tmp/glide/${GLIDE_OS_ARCH}
- sudo apt-get update -q
- sudo apt-get install upx -y
install: glide install
after_success:
- |-
  echo "After Success:"
  echo $TRAVIS_TAG
  echo $TRAVIS_GO_VERSION
  if [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_GO_VERSION" == "1.8.3" ]
  then
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_TAG" -o claptrap-linux-amd64
    CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_TAG" -o claptrap-darwin-amd64
    CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_TAG" -o claptrap-windows-amd64
  fi
script: go test --cover $(go list ./... | grep -v '/vendor/')

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SvXwnmtTcEJTKtjtbEQHi71+CblEGjNqFQLbUSqk+Y9fe49k9PmaMR6ROlI629FqGIoOIKIhHK5NKPC6lC18HlOV1cwgH6fBeZUk2VmuKSJwpJRUmEAk9FkMmdZVY0C3OxiDlt7vnISpw55iGX52VC83J3o5XNjlwbbd1Wmi9rEk4ot9WhoZCoTZxxxiNUji/QQt20905ZNmxpAfe++gIE9UIV4vP3uArDQ2Bk9pqclXAFBpb8+8eFxoYHkl/fNoUglAmINj3osMxNAn9UQ5luDGu4++XxXZJPwEg1q4cJQcJNZZdjNYni2VvDO+gJLgEY2opV4auU+4RKqR5iwIVk0ICOcnOvGH/KK8KEpP/wDgWxr1xAlZTUW5jZxLTmCCax4S14rPOFJVr+F6x6RYwa3+98JBi/WM708zqf2PDBaphl7Z4c4iIH39nogRk2Gj/OqyqZLmkDcfXloC5/Bl4tPGEeT2IuxsaICWEcusngTlZNDWYs7BxOIKkqMo/ZWsAahMSPTejVjZMjP61/JQVwMdHtSfzeBB80jLxZJFBnABhAzr3v8iSlSdRtlW27qk+eWYhmGI77JmHw0DXQ1C/a9l5VGn/XDCbct6uEl3lrYokBqe15DfNkPsqMVJlUGJGQOUSoUS9pNxzN6y0ZwT3UT0GOGCLatJMll48ARiwTw=
    file:
      - claptrap-linux-amd64
      - claptrap-darwin-amd64
      - claptrap-windows-amd64
  on:
    repo: alexshemesh/claptrap
    condition: $TRAVIS_GO_VERSION = 1.8.3
    tags: true
