sudo: required
language: go
go:
- 1.10.1
before_install:
- GLIDE_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
- GLIDE_TAG=$(curl -s https://glide.sh/version)
- GLIDE_LATEST_RELEASE_URL="https://github.com/Masterminds/glide/releases/download/${GLIDE_TAG}/glide-${GLIDE_TAG}-${GLIDE_OS_ARCH}.tar.gz"
- wget ${GLIDE_LATEST_RELEASE_URL} -O /tmp/glide.tar.gz
- mkdir /tmp/glide
- tar --directory=/tmp/glide -xvf /tmp/glide.tar.gz
- export PATH=$PATH:/tmp/glide/${GLIDE_OS_ARCH}
- sudo apt-get update -q
- sudo apt-get install upx -y
install: glide install
after_success:
- |-
  echo "After Success:"
  echo $TRAVIS_TAG
  echo $TRAVIS_GO_VERSION
  if [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_GO_VERSION" == "1.10.1" ]
  then
    mkdir build
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_TAG" -o build/claptrap-linux-amd64
    CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_TAG" -o build/claptrap-darwin-amd64
    CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_TAG" -o build/claptrap-windows-amd64
  fi
script: go test --cover $(go list ./... | grep -v '/vendor/')
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAJ5V4JN6IDPX5TLTA
  secret_access_key:
    secure: IENjqRs/mIOxK9GT4bxeOIt3vj3+VZOKd0cXVjXnB1c/iTOpVVJfq1GtmswL0yMpxCmWX9qijDZw8uxLIP8UNzNHdnqDEsxeOwGB+hQowZXIXFByv9qpnmIjjRVk9YKtblB4iBjLorshYqPKUB0W/Yf7JABbAhWUoO9XruarM7X0QEHgwV3/pHueX+QgCLtESyXXvSOz6kcnhlVZYsr6f6wu1aMdp8pf1ib3+dzIUsO9X4w+H3+11y9m9vX/AdFBOAYYezyPnqS0HiZiB1xra9QMW8JOOTxbiXEuCEDHrBPoXEdS47LRoCyLziCbIZWrYnRl0N70XGzIywaGqNOYAVcFtG0lVxA05H+j8ZzRwKhsvGF7e977t8OkiUpWJhK7iuVDlwBqiSJwTWdfJ/7mC2385bL40zxxhDnHFQIqay3ObRjXCt6Z1XFuY8x+m10nr1lxmlIQVHQUGPDaSLue/h1CpquUINU/Z4FkJHvf3x7pwJ5CviiA6NztQEhzrx1ZAyGS/V4kCIliRh/8/jf/tM7dd41vyuRPXST9kkJMtkEfSqR+0WcqNyCsVtKyTOP5BwXP+OcWKvXlWoBGwSafh2MqFJFV9WE4OTZ2pM6vHbaY3EgjyKIT3A9lwZ5E+OIUJhoDImmPE2tvXVH3V3qJH7IrmOhUopKWNSHIHcqQ7Ag=
  bucket: files.ctt-ops.com
  acl: authenticated_read
  on:
    repo: alexshemesh/claptrap
    condition: "$TRAVIS_GO_VERSION = 1.10.1"
    tags: true
  local_dir: build
