sudo: required
language: go
go:
- 1.10.1
before_install:
- GLIDE_OS_ARCH=`go env GOHOSTOS`-`go env GOHOSTARCH`
- GLIDE_TAG=$(curl -s https://glide.sh/version)
- GLIDE_LATEST_RELEASE_URL="https://github.com/Masterminds/glide/releases/download/${GLIDE_TAG}/glide-${GLIDE_TAG}-${GLIDE_OS_ARCH}.tar.gz"
- wget ${GLIDE_LATEST_RELEASE_URL} -O /tmp/glide.tar.gz
- mkdir /tmp/glide
- tar --directory=/tmp/glide -xvf /tmp/glide.tar.gz
- export PATH=$PATH:/tmp/glide/${GLIDE_OS_ARCH}
- sudo apt-get update -q
- sudo apt-get install upx -y
install: glide install
after_success:
- |-
  echo "After Success:"
  echo $TRAVIS_JOB_NUMBER
  echo $TRAVIS_GO_VERSION
  if[ "$TRAVIS_GO_VERSION" == "1.10.1" ]
  then
    mkdir build
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_JOB_NUMBER" -o build/claptrap-linux-amd64-$TRAVIS_JOB_NUMBER
    CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_JOB_NUMBER" -o build/claptrap-darwin-amd64-$TRAVIS_JOB_NUMBER
    CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.Version=$TRAVIS_JOB_NUMBER" -o build/claptrap-windows-amd64-$TRAVIS_JOB_NUMBER
  fi
script: go test --cover $(go list ./... | grep -v '/vendor/')
deploy:
  provider: s3
  access_key_id: AKIAJ5V4JN6IDPX5TLTA
  secret_access_key:
    secure: do6QtzM9DmT3NBxJC5gJj2l8QnMQ7mxqQrLA2Dd0vJLRcr+f/rDevf9FmzhBD/xMUcC9v811+ckGmsO36k0aT3OOCgcI40z6HlzZGoRSiLuNVjT/KTorhzPKbM2WIn5bxR/0uM6y7sg/kvV9UQOvc55vkK7qFZSwTxgkN3NpMLKUl1l6Hyc5iqyZy7XGfaSv8SrtVAYRt5UazNRK5hCx3Up4+ctsRF/m7GwKGuVqH/Zmxc1ml2uW+2EZutdzXFXXmWxufpqjrLi/syOY//WtnKDVIZRTe4AQLKw0IlmxucCENtQiR4BzQYahMlkpkxjFPfJ2ArH8YZCZQTJJdVJP/Y8yXSLEKw29ojWsV0VsPO31vJW4mOl5oSqgN+5FPzkppwy1QM9jZgAZpS526Lu9OZLz7LjJ4dVzGcrTUj11ATNa3wcIqNp7tUBNrrz8IrV939cCF1P2P0HJlGc8iqRwVFOamIkW3vU5V9TwCy4D4STTXyitV/vQdhlwTfgdvsIfFWV0F4PI7RwY2PNxpx5u3ad4Ois9r8Kn3Ovk3IwcDOjqirmmaCIob72/+hdtLHh+ETH+oBUOD4Ibyv3ygNxvEGRkvCVOs4C2PiO7tk7w4R92zUBM6HcdfTXrPQCoXOI0mxt3nApU3jgGjq/J7gb4K4HdlQPNUcfiU4ZqYsZQQfA=
  bucket: files.cct-ops.com
  local-dir: build
  acl: private
  region: eu-west-1
  skip_cleanup: true
  on:
    repo: alexshemesh/claptrap
    tags: true
